### PR TITLE
Travis CI integration fixed

### LINKED ISSUE #1: Integrate Travis CI

### PR DESCRIPTION
**Pull request by SignpostMarv**
Tweaked the code & travis config to get phpunit to behave as expected on travis ci- compare [before](https://travis-ci.org/ankitjain28may/registration-module/jobs/164282407) & [after](https://travis-ci.org/SignpostMarv/registration-module/builds/171858453), should fix #1 

p.s. is for hacktoberfest :P

### CODE REVIEW

**Comment by ankitjain28may** [comment]
Thanks alot.. Can you please send the pr to the contribution branch so I can merge it..?

**Comment by ankitjain28may** [comment]
N can you please tell me how to setup Travis CI ?

**Comment by SignpostMarv** [comment]
The travis config file is in there, so all you'd need to do is sign in to travis-ci.org & turn this repo on in your account.

**Comment by ankitjain28may** [comment]
I hve tried that too.. Bt still I was unable to set up it.. Can u please refer me a doc so I can learn about it and phpunit..!

**Comment by SignpostMarv** [comment]
https://docs.travis-ci.com/user/for-beginners

**Comment by ankitjain28may** [comment]
Hello.. I hve seen that u hve setup phpunit test only fr testing whether this class exists or not... , its nt testing whether this module is working as expected or not..?

**Comment by SignpostMarv** [comment]
You'll need to write more tests.

**Comment by ankitjain28may** [comment]
Ok

**Pull request merged**
